// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASZFBgfmyOm-jcbW5bCKeK8Zz_PLK34Wc',
    appId: '1:632711552292:web:67a1beff03a40b55dce7b1',
    messagingSenderId: '632711552292',
    projectId: 'yzta-bootcamp-group110',
    authDomain: 'yzta-bootcamp-group110.firebaseapp.com',
    storageBucket: 'yzta-bootcamp-group110.firebasestorage.app',
    measurementId: 'G-K84NNKZRHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJqKxcZHEkfMhjmydWUUpVHiIR5f1vj8c',
    appId: '1:632711552292:android:4600c9d87e6923bddce7b1',
    messagingSenderId: '632711552292',
    projectId: 'yzta-bootcamp-group110',
    storageBucket: 'yzta-bootcamp-group110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIKKryjOzfIcIAiJDf_XnJHezmnHFmOo',
    appId: '1:632711552292:ios:24f1151c577aa8fddce7b1',
    messagingSenderId: '632711552292',
    projectId: 'yzta-bootcamp-group110',
    storageBucket: 'yzta-bootcamp-group110.firebasestorage.app',
    iosBundleId: 'com.example.smartMedAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtIKKryjOzfIcIAiJDf_XnJHezmnHFmOo',
    appId: '1:632711552292:ios:24f1151c577aa8fddce7b1',
    messagingSenderId: '632711552292',
    projectId: 'yzta-bootcamp-group110',
    storageBucket: 'yzta-bootcamp-group110.firebasestorage.app',
    iosBundleId: 'com.example.smartMedAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASZFBgfmyOm-jcbW5bCKeK8Zz_PLK34Wc',
    appId: '1:632711552292:web:3be893b30527586cdce7b1',
    messagingSenderId: '632711552292',
    projectId: 'yzta-bootcamp-group110',
    authDomain: 'yzta-bootcamp-group110.firebaseapp.com',
    storageBucket: 'yzta-bootcamp-group110.firebasestorage.app',
    measurementId: 'G-6W0RBVBKCN',
  );
}
