// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxE2EgBawqPazGb8b7HgzBHwezOWkL9Tk',
    appId: '1:424436659545:web:5068895cba3c1948dfc848',
    messagingSenderId: '424436659545',
    projectId: 'medimate-90d89',
    authDomain: 'medimate-90d89.firebaseapp.com',
    storageBucket: 'medimate-90d89.firebasestorage.app',
    measurementId: 'G-BSCGNQ2NQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB58-HqUnPB07BtzSIwAj0NDzwlcXaTqaA',
    appId: '1:424436659545:android:31e6e3edf8cc66bfdfc848',
    messagingSenderId: '424436659545',
    projectId: 'medimate-90d89',
    storageBucket: 'medimate-90d89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAkt4BexXrrphHNPtA2f3YWK-ArJPDByI',
    appId: '1:424436659545:ios:02ce437519e05022dfc848',
    messagingSenderId: '424436659545',
    projectId: 'medimate-90d89',
    storageBucket: 'medimate-90d89.firebasestorage.app',
    iosBundleId: 'com.example.smartMedAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAkt4BexXrrphHNPtA2f3YWK-ArJPDByI',
    appId: '1:424436659545:ios:02ce437519e05022dfc848',
    messagingSenderId: '424436659545',
    projectId: 'medimate-90d89',
    storageBucket: 'medimate-90d89.firebasestorage.app',
    iosBundleId: 'com.example.smartMedAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxE2EgBawqPazGb8b7HgzBHwezOWkL9Tk',
    appId: '1:424436659545:web:c640aa92b8a2fd2adfc848',
    messagingSenderId: '424436659545',
    projectId: 'medimate-90d89',
    authDomain: 'medimate-90d89.firebaseapp.com',
    storageBucket: 'medimate-90d89.firebasestorage.app',
    measurementId: 'G-QQFEM6756T',
  );

}